
var dogBreeds = {
    "affenpinscher": "affenpinscher",
    "african": "african",
    "airedale": "airedale",
    "akita": "akita",
    "appenzeller": "appenzeller",
    "australian-shepherd": "shepherd australian",
    "basenji": "basenji",
    "beagle": "beagle",
    "bluetick": "bluetick",
    "borzoi": "borzoi",
    "bouvier": "bouvier",
    "boxer": "boxer",
    "brabancon": "brabancon",
    "briard": "briard",
    "buhund-norwegian": "norwegian buhund",
    "bulldog-boston": "boston bulldog",
    "bulldog-english": "english bulldog",
    "bulldog-french": "french bulldog",
    "bullterrier-staffordshire": "staffordshire bullterrier",
    "cattledog-australian": "australian cattledog",
    "chihuahua": "chihuahua",
    "chow": "chow",
    "clumber": "clumber",
    "cockapoo": "cockapoo",
    "collie-border": "border collie",
    "coonhound": "coonhound",
    "corgi-cardigan": "cardigan corgi",
    "cotondetulear": "cotondetulear",
    "dachshund": "dachshund",
    "dalmatian": "dalmatian",
    "dane-great": "great dane",
    "deerhound-scottish": "scottish deerhound",
    "dhole": "dhole",
    "dingo": "dingo",
    "doberman": "doberman",
    "elkhound-norwegian": "norwegian elkhound",
    "entlebucher": "entlebucher",
    "eskimo": "eskimo",
    "finnish-lapphund": "lapphund finnish",
    "frise-bichon": "bichon frise",
    "germanshepherd": "germanshepherd",
    "golden": "golden",
    "greyhound-italian": "italian greyhound",
    "groenendael": "groenendael",
    "havanese": "havanese",
    "hound-afghan": "afghan hound",
    "hound-basset": "basset hound",
    "hound-blood": "blood hound",
    "hound-english": "english hound",
    "hound-ibizan": "ibizan hound",
    "hound-plott": "plott hound",
    "hound-walker": "walker hound",
    "husky": "husky",
    "keeshond": "keeshond",
    "kelpie": "kelpie",
    "komondor": "komondor",
    "kuvasz": "kuvasz",
    "labradoodle": "labradoodle",
    "labrador": "labrador",
    "leonberg": "leonberg",
    "lhasa": "lhasa",
    "malamute": "malamute",
    "malinois": "malinois",
    "maltese": "maltese",
    "mastiff-bull": "bull mastiff",
    "mastiff-english": "english mastiff",
    "mastiff-tibetan": "tibetan mastiff",
    "mexicanhairless": "mexicanhairless",
    "mix": "mix",
    "mountain-bernese": "bernese mountain",
    "mountain-swiss": "swiss mountain",
    "newfoundland": "newfoundland",
    "otterhound": "otterhound",
    "ovcharka-caucasian": "caucasian ovcharka",
    "papillon": "papillon",
    "pekinese": "pekinese",
    "pembroke": "pembroke",
    "pinscher-miniature": "miniature pinscher",
    "pitbull": "pitbull",
    "pointer-german": "german pointer",
    "pointer-germanlonghair": "germanlonghair pointer",
    "pomeranian": "pomeranian",
    "poodle-medium": "medium poodle",
    "poodle-miniature": "miniature poodle",
    "poodle-standard": "standard poodle",
    "poodle-toy": "toy poodle",
    "pug": "pug",
    "puggle": "puggle",
    "pyrenees": "pyrenees",
    "redbone": "redbone",
    "retriever-chesapeake": "chesapeake retriever",
    "retriever-curly": "curly retriever",
    "retriever-flatcoated": "flatcoated retriever",
    "retriever-golden": "golden retriever",
    "ridgeback-rhodesian": "rhodesian ridgeback",
    "rottweiler": "rottweiler",
    "saluki": "saluki",
    "samoyed": "samoyed",
    "schipperke": "schipperke",
    "schnauzer-giant": "giant schnauzer",
    "schnauzer-miniature": "miniature schnauzer",
    "segugio-italian": "italian segugio",
    "setter-english": "english setter",
    "setter-gordon": "gordon setter",
    "setter-irish": "irish setter",
    "sharpei": "sharpei",
    "sheepdog-english": "english sheepdog",
    "sheepdog-shetland": "shetland sheepdog",
    "shiba": "shiba",
    "shihtzu": "shihtzu",
    "spaniel-blenheim": "blenheim spaniel",
    "spaniel-brittany": "brittany spaniel",
    "spaniel-cocker": "cocker spaniel",
    "spaniel-irish": "irish spaniel",
    "spaniel-japanese": "japanese spaniel",
    "spaniel-sussex": "sussex spaniel",
    "spaniel-welsh": "welsh spaniel",
    "springer-english": "english springer",
    "stbernard": "stbernard",
    "terrier-american": "american terrier",
    "terrier-australian": "australian terrier",
    "terrier-bedlington": "bedlington terrier",
    "terrier-border": "border terrier",
    "terrier-cairn": "cairn terrier",
    "terrier-dandie": "dandie terrier",
    "terrier-fox": "fox terrier",
    "terrier-irish": "irish terrier",
    "terrier-kerryblue": "kerryblue terrier",
    "terrier-lakeland": "lakeland terrier",
    "terrier-norfolk": "norfolk terrier",
    "terrier-norwich": "norwich terrier",
    "terrier-patterdale": "patterdale terrier",
    "terrier-russell": "russell terrier",
    "terrier-scottish": "scottish terrier",
    "terrier-sealyham": "sealyham terrier",
    "terrier-silky": "silky terrier",
    "terrier-tibetan": "tibetan terrier",
    "terrier-toy": "toy terrier",
    "terrier-welsh": "welsh terrier",
    "terrier-westhighland": "westhighland terrier",
    "terrier-wheaten": "wheaten terrier",
    "terrier-yorkshire": "yorkshire terrier",
    "tervuren": "tervuren",
    "vizsla": "vizsla",
    "waterdog-spanish": "spanish waterdog",
    "weimaraner": "weimaraner",
    "whippet": "whippet",
    "wolfhound-irish": "irish wolfhound"
};


export default dogBreeds;